### ISSUE TITLE
notebook.ipynb exist???

### ISSUE THREAD

**Issue by raismartup** [locomotive-agency/GA3toGA4#1]
Hello!

Congralutations for your project!!! It´s fantastic.

I have a question about this. In the repository you talk about a notebook but I don't see one notebok.ipynb, should there really be one?

Thank so much :)

**Comment by joejoinerr** [comment]
Hey @raismartup 👋 The notebook that you need is on Google Colab here: https://colab.research.google.com/drive/1X7bWFcxsoe2WJ892vbbpsERNurv28k7S?usp=sharing. You can select File > Save a copy... to create your own editable version.

I'll update the README to make this more clear :)
