### ISSUE TITLE
Table GA3 does not exist

### ISSUE THREAD

**Issue by raismartup** [locomotive-agency/GA3toGA4#3]
Hi again my friend!

I have managed to set up all the steps you indicate in the notebook but I am stuck in step 4: backfill GA3 data

My question is the following: is it necessary to have a table created in bigquery with the GA3 data version?
If yes, is it possible to export the GA3 data to a bigquery table? because I have only seen that it can be done with the GA4 version.

Thank so much :)

Best.
Rai

**Comment by joejoinerr** [comment]
Hey @raismartup,

If I understand your question correctly: no, it's not necessary to have your GA3 data in BigQuery before running step 4. You do not need to manually create anything in BigQuery - by following the steps in the notebook, the tool will create the BigQuery table and fill it with data. The GA3 data will be downloaded from the API and merged with the the GA4 data.

Does that help you to move forward?

**Comment by raismartup** [comment]
Hi!

thanks for your quick response :)

I just realized that's exactly what it does, but I didn't know exactly what to put in the **ga3_view_id** parameter and I know that you have to put the ID of the project you want to fill with the GA4 table.

Also, the **goal_metric** parameter to want to take all the metrics, is it enough to leave it like that? or you have to put another value that indicates that you want to bring you everything?

On the other hand (taking the opportunity to reply to this thread) there is a limit of history that you can join, isn't it? 100.000 rows for example??

Thanks :)

**Comment by joejoinerr** [comment]
@raismartup Yes, `ga3_view_id` must be a valid ID from the rightmost (Views) column in the Google Analytics interface. You can see an example here:

![2022-07-29 09_22_25-Clipboard](https://user-images.githubusercontent.com/2454320/181716998-f2b952c8-217f-4560-9a42-94d410cf42a5.png)

 The default `goal_metric` is ga:goalCompletionsAll. You can leave it as that to pull all of the goal completions as a single total.

I'm not aware of any history limit. You can set the `pull_start_date` to designate how many days you want to look back.

**Comment by raismartup** [comment]
Thank so much for you help! :)
